travis:
  secure:
    BINSTAR_TOKEN: PhIMMux9Zo4CO6Bz+JaZyLcHbKVeiTXA2naCiqmFhLvx+vQymFfqzLFgme0drvP0tWHWKQK+pXBEAgSzel4MT8B2sCn7e6asg8Yp2WzEWvEM88INyo+ES5BhxC64y46CShb+A+MwL+yNIgLWywHu7bhfG8e39tfRQks4ZuEbDDqzmq/OQgJLNZ8+hcBhQaH/eL98DaBfV4Qilj+imURReeMx8T+Iq8HU5NsGhlgKbC/a8IEJNUZDGfY+zu3okImTbqSr2ngwt+zfDoQ04+s1jkC15fCpKGtlRf8hhu5KaJuknNmanHZWV6dtKPCf574bdmJ/0HnNUvsIj8sZj35BRWLNN3q4fTyXetrnbQR99MmPnLVqvrLNX9KPJj+1Vkmz3GdhFX6YBR46i6WOEObVcRZMMIAHvjvSd+i2c6mne/rkQNLbtBjHvKmyKkvGInEiRR36Va+objN2BdYGT8lerHkw7XzlSTfAtCsFQQ1R9G8pk2wo8dzpC8mnOCOA/2oEybaa/7LNIWOP9CHbeDWunIxZvr65BC/WWcwDwdiI3HDEpH7WBoLYWU95g7K8XzV0rOGo6VLvmhQP48vOHU0q83qoSDBg0rN6vEfg2jab4V+ijX6ioGaJYoePTaCRAKS9leMvLo77jcVrwBmOWWHjXYQW1BJdUe6Pfmu21+M4f2M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
